          - name: Add debian testing repository
            apt_repository:
                    repo: deb-src http://ftp.de.debian.org/debian testing main
                    state: present

          - name: Install apt-utils
            apt:
                    name: apt-utils
                    state: present

          - name: Check Python3.6 installation
            command: which python3.6
            register: python36_check
            ignore_errors: yes

          - name: Install python3.6
            shell: env -i PATH=$PATH bash -c "apt-get build-dep -y python3.6"
            when: python36_check is failed

          - name: Make directory /home/src
            file:
              path: /home/src
              state: directory


          - name: Download python 3.6.5 in /home/src
            get_url:
              url: https://www.python.org/ftp/python/3.6.5/Python-3.6.5.tgz
              dest: /home/src/
            when: python36_check is failed


          - name: Unzip Python-3.6.5.tgz
            unarchive:
              src: /home/src/Python-3.6.5.tgz
              dest: /home/src/
              remote_src: yes
            when: python36_check is failed


          - name: Configure and install python 3.6.5
            shell: ./configure && make && make altinstall
            args:
              chdir: /home/src/Python-3.6.5
            when: python36_check is failed

#          - shell: env -i PATH=$PATH bash -c "pip3.6 install jupyter virtualenvwrapper"

          - name: Install Django 2.0.4
            pip:
              executable: pip3.6
              name: Django
              version: 2.0.4

          - name: Install pymongo 3.6.1
            pip:
              executable: pip3.6
              name: pymongo
              version: 3.6.1
           
          - name: Install jsonschema
            pip:
              executable: pip3.6
              name: jsonschema

